# Generated by Django 4.2.2 on 2024-02-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='post',
    #         name='intro',
    #     ),
    # ]
